name: Build Latex PDF

on:
  push:
    paths:
      - "**.tex"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build LaTeX Document
      uses: lyuwen/build-latex-action@v1.0.1
      with:
        # Name of the file to build.
        file: 'Dark Souls Respeccing Problem Solution/main.tex'
