name: Build Latex PDF

on:
  push:
    paths:
      - "**.tex"
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Build LaTeX
      run: |
        sudo apt install latexmk
        cd latex
        latexmk -pdf main.tex 
        latexmk -c
