name: Build Latex PDF

on:
  push:
    paths:
      - "**.tex"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - name: Download LaTeXMK
      run: |
        sudo apt install latexmk
    - name: Build LaTeX
      run: |
        cd latex
        latexmk -pdf main.tex 
        latexmk -c
